namespace :card_sources do
  desc 'Sets the sources for various cards, including buy price'
  task set: :environment do
    puts 'Setting various card sources'

    # Initial
    Card.where(name: %w(Dodo Sabotender Bomb Mandragora Couerl)).update(source: 'Quest: Triple Triad Trial')

    # Dungeon/Trial/Raid
    Card.find_by(name: 'Zenos yae Galvus').update(source: 'Ala Mhigo')
    Card.find_by(name: 'Grynewaht').update(source: 'Doma Castle')
    Card.find_by(name: 'Ferdiad').update(source: 'Amdapor Keep (Hard)')
    Card.find_by(name: 'Demon Wall').update(source: 'Amdapor Keep, Amdapor Keep (Hard)')
    Card.find_by(name: 'Morbol').update(source: 'Aurum Vale')
    Card.find_by(name: 'The Griffin').update(source: "Baelsar's Wall")
    Card.find_by(name: 'Livia sas Junius').update(source: 'Castrum Meridiaum')
    Card.find_by(name: 'Chimera').update(source: "Cutter's Cry")
    Card.find_by(name: 'Ahriman').update(source: 'Dzemael Darkhold')
    Card.find_by(name: 'Succubus').update(source: 'Haukke Manor, Haukke Manor (Hard)')
    Card.find_by(name: 'Mistbeard').update(source: 'Hullbreaker Isle (Hard)')
    Card.find_by(name: 'Waukkeon').update(source: 'Neverreap')
    Card.find_by(name: 'Siren').update(source: 'Pharos Sirius')
    Card.find_by(name: 'Progenitrix').update(source: 'Pharos Sirius (Hard)')
    Card.find_by(name: 'Belladonna').update(source: "Saint Mocianne's Arboretum")
    Card.find_by(name: 'Tokkapchi').update(source: "Saint Mocianne's Arboretum (Hard)")
    Card.find_by(name: 'Sahagin').update(source: 'Sastasha, Sastasha (Hard)')
    Card.find_by(name: 'Kraken').update(source: 'Sastasha (Hard)')
    Card.find_by(name: 'Lava Scorpion').update(source: 'Sohm Al (Hard)')
    Card.find_by(name: 'Hraesvelgr').update(source: 'Sohr Khai')
    Card.find_by(name: 'Calcabrina').update(source: 'The Antitower')
    Card.find_by(name: 'Mist Dragon').update(source: 'The Burn')
    Card.find_by(name: 'Tioman').update(source: 'Sohm Al')
    Card.find_by(name: 'Nidhogg').update(source: 'The Aery')
    Card.find_by(name: 'Griffin').update(source: 'Dusk Vigil')
    Card.find_by(name: 'Byblos').update(source: 'The Great Gubal Library')
    Card.find_by(name: 'Strix').update(source: 'The Great Gubal Library (Hard)')
    Card.find_by(name: 'Curator').update(source: 'The Fractal Continuum')
    Card.find_by(name: 'Kuribu').update(source: 'The Lost City of Amdapor (Hard)')
    Card.find_by(name: 'Blue Dragon').update(source: 'Stone Vigil, Stone Vigil (Hard)')
    Card.find_by(name: 'Vicegerent to the Warden').update(source: 'The Sunken Temple of Qarn (Hard)')
    Card.find_by(name: 'Charibert').update(source: 'The Vault')
    Card.find_by(name: 'Manxome Molaa Ja Ja').update(source: "The Wanderer's Palace (Hard)")
    Card.find_by(name: 'Tonberry').update(source: "The Wanderer's Palace, The Wanderer's Palace (Hard)")
    Card.find_by(name: 'Tozol Huatotl').update(source: 'Xelphatol')
    Card.find_by(name: 'Genbu').update(source: "Hell's Lid")
    Card.find_by(name: 'Guidance Node').update(source: 'The Fractal Continuum (Hard)')
    Card.find_by(name: 'Qitian Dasheng').update(source: "The Swallow's Compass")
    Card.find_by(name: 'Fenrir').update(source: 'Snowcloak')
    Card.find_by(name: 'Hrodric Poisontongue').update(source: 'The Drowned City of Skalla')

    # Trials
    Card.find_by(name: 'Zurvan').update(source: 'Containment Bay Z1T9, Containment Bay Z1T9 (Extreme)')
    Card.find_by(name: 'Shiva').update(source: 'Akh Afah Amphitheatre (Hard), Akh Afah Amphitheatre (Extreme)')
    Card.find_by(name: 'Rhitahtyn sas Arvina').update(source: 'Cape Westwind')
    Card.find_by(name: 'Bartz Klauser').update(source: 'Battle in the Big Keep')
    Card.find_by(name: 'Gilgamesh & Enkidu').update(source: 'Battle on the Big Bridge')
    Card.find_by(name: 'Suzaku').update(source: "Hells' Kier, Hells' Kier (Extreme)")
    Card.find_by(name: 'Sophia').update(source: 'Containment Bay P1T6, Containment Bay P1T6 (Extreme)')
    Card.find_by(name: 'Ifrit').update(source: 'The Bowl of Embers (Hard), The Bowl of Embers (Extreme)')
    Card.find_by(name: 'Ultros & Typhon').update(source: "The Dragon's Neck")
    Card.find_by(name: 'Terra Branford').update(source: "The Dragon's Neck")
    Card.find_by(name: 'Garuda').update(source: 'The Howling Eye (Hard), The Howling Eye (Extreme)')
    Card.find_by(name: 'Bismarck').update(source: 'The Limitless Blue (Hard), The Limitless Blue (Extreme)')
    Card.find_by(name: 'Archbishop Thordan VII').update(source: "The Minstrel's Ballad: Thordan's Reign")
    Card.find_by(name: 'Ultima Weapon').update(source: "The Minstrel's Ballad: Ultima's Bane")
    Card.find_by(name: 'Titan').update(source: 'The Navel (Hard), The Navel (Extreme)')
    Card.find_by(name: 'Ramuh').update(source: 'The Striking Tree (Hard), The Striking Tree (Extreme)')
    Card.find_by(name: 'Leviathan').update(source: 'The Whorleater (Hard), The Whorleater (Extreme)')
    Card.find_by(name: 'Ravana').update(source: 'Thok ast Thok (Hard), Thok ast Thok (Extreme)')
    Card.find_by(name: 'Good King Moggle Mog XII').update(source: 'Thornmarch (Hard), Thornmarch (Extreme)')
    Card.find_by(name: 'Odin').update(source: "Urth's Fount")
    Card.find_by(name: 'Tsukuyomi').update(source: "Castrum Fluminis, The Minstrel's Ballad: Tsukuyomi's Pain")
    Card.find_by(name: 'Byakko').update(source: 'The Jade Stoa, The Jade Stoa (Extreme)')
    Card.find_by(name: 'Lakshmi').update(source: 'Emanation, Emanation (Extreme)')
    Card.find_by(name: 'Susano').update(source: 'The Pool of Tribute, The Pool of Tribute (Extreme)')
    Card.find_by(name: 'Shinryu').update(source: "The Royal Menagerie, The Minstrel's Ballad: Shinryu's Domain")

    # Raids
    Card.find_by(name: 'Phlegethon').update(source: 'Labyrinth of the Ancients')
    Card.find_by(name: 'Diabolos Hollow').update(source: 'Dun Scaith')
    Card.find_by(name: 'Brute Justice').update(source: 'Alexander - The Burden of the Son')
    Card.find_by(name: 'Alexander Prime').update(source: 'Alexander - The Soul of the Creator')
    Card.find_by(name: 'Omega').update(source: 'Alphascape V3.0, Alphascape V4.0')
    Card.find_by(name: 'Xande').update(source: 'Syrcus Tower')
    Card.find_by(name: 'Echidna').update(source: 'The Void Ark')
    Card.find_by(name: 'Calofisteri').update(source: 'The Weeping City of Mhach')
    Card.find_by(name: 'Cloud of Darkness').update(source: 'World of Darkness')
    Card.find_by(name: 'Onion Knight').update(source: 'World of Darkness')
    Card.find_by(name: 'Yiazmat').update(source: 'The Ridorana Lighthouse')
    Card.find_by(name: 'Rofocale').update(source: 'The Royal City of Rabanastre')
    Card.find_by(name: 'Argath Thadalfus').update(source: 'The Royal City of Rabanastre')

    # FATEs
    Card.find_by(name: 'Darkscale').update(source: 'FATE: Mogicide / Rastaban Vibration (Churning Mists)')
    Card.find_by(name: 'Fat Chocobo').update(source: 'FATE: Special Tarasque Force (Dravanian Forelands)')
    Card.find_by(name: 'Phoebad').update(source: 'FATE: Tall Tale (The Lochs)')
    Card.find_by(name: 'Mammoth').update(source: 'FATE: Wham, Bam, Thank You Mammoth (Azim Steppe)')

    # Eureka
    Card.find_by(name: 'Happy Bunny').update(source: 'Eureka Pagos: Silver Coffer')
    Card.find_by(name: 'Yukinko').update(source: 'Eureka Pagos: Eternity FATE')
    Card.find_by(name: 'Pazuzu').update(source: 'Eureka Anemos: Pazuzu')
    Card.find_by(name: 'Louhi').update(source: 'Eureka Pagos: Louhi')
    Card.find_by(name: 'Penthesilea').update(source: 'Eureka Pyros: Penthesilea')

    # Heaven on High
    Card.find_by(name: 'Wanyudo & Katasharin').update(source: 'Heaven on High: Silver/Gold Sack')
    Card.find_by(name: 'Hatamoto').update(source: 'Heaven on High: Silver/Gold Sack')
    Card.find_by(name: 'Hiruko').update(source: 'Heaven on High: Gold Sack')

    # Achievements
    Card.find_by(name: 'Heavensward Thancred').update(source: 'Achievement: Triple Team V')
    Card.find_by(name: 'Midgardsormr').update(source: 'Achievement: Triple Decker IV')
    Card.find_by(name: 'Vidofnir').update(source: 'Achievement: Triple Decker V')
    Card.find_by(name: "Heavensward Y'shtola").update(source: 'Achievement: Triple-Decker VI')
    Card.find_by(name: 'Lyse').update(source: 'Achievement: Triple-Decker VII')
    Card.find_by(name: 'Gosetsu').update(source: 'Achievement: Triple Decker VIII')
    Card.find_by(name: 'Shantotto').update(source: 'Achievement: Kumite Kumite Kumite')
    Card.find_by(name: 'Squall Leonhart').update(source: 'Achievement: Triple Team II')
    Card.find_by(name: 'Haurchefant').update(source: 'Achievement: Triple Team III')
    Card.find_by(name: 'Krile').update(source: 'Achievement: Triple Team VII')
    Card.find_by(name: 'Vaan').update(source: 'Achievement: Wheel of Fortune V')

    # Events
    Card.find_by(name: 'Gold Saucer Attendant').update(source: 'Event: Make It Rain (500 MGP)')
    Card.find_by(name: 'Roland').update(source: 'Event: Make It Rain (1,000 MGP)')
    Card.find_by(name: 'Gigi').update(source: 'Event: Make It Rain (18,000 MGP)')

    # Shop prices
    Card.find_by(name: 'Chocobo').update(buy_price: 600)
    Card.find_by(name: 'Opo-opo').update(buy_price: 600)
    Card.find_by(name: 'Moogle').update(buy_price: 840)
    Card.find_by(name: 'Mossling').update(buy_price: 840)
    Card.find_by(name: 'Adamantoise').update(buy_price: 840)
    Card.find_by(name: 'Chapuli').update(buy_price: 1200)
    Card.find_by(name: 'Muud Suud').update(buy_price: 1500)
    Card.find_by(name: 'Raya-O-Senna & A-Ruhn-Senna').update(buy_price: 4800)
    Card.find_by(name: 'Godbert Manderville').update(buy_price: 9600)
    Card.find_by(name: 'Julyan Manderville').update(buy_price: 14_400)
    Card.find_by(name: "F'lhaminn").update(buy_price: 20_000)
    Card.find_by(name: 'Senor Sabotender').update(buy_price: 200_000)
    Card.find_by(name: 'Nanamo Ul Namo').update(buy_price: 400_000)
    Card.find_by(name: 'Raubahn & Pipin').update(buy_price: 400_000)
    Card.find_by(name: 'Cloud Strife').update(buy_price: 1_000_000)
  end
end
