namespace :card_sources do
  desc 'Sets the sources for various cards, including buy price'
  task set: :environment do
    puts 'Setting various card sources'

    # Initial
    Card.where(name_en: %w(Dodo Sabotender Bomb Mandragora Coeurl)).each do |card|
      card.sources.find_or_create_by!(origin: 'Other', name: 'Quest: Triple Triad Trial')
    end

    # Dungeon
    Card.find_by(name: 'Gaius van Baelsar').sources.find_or_create_by(origin: 'Dungeon', name: 'The Praetorium')
    Card.find_by(name: 'Zenos yae Galvus').sources.find_or_create_by(origin: 'Dungeon', name: 'Ala Mhigo')
    Card.find_by(name: 'Grynewaht').sources.find_or_create_by(origin: 'Dungeon', name: 'Doma Castle')
    Card.find_by(name: 'Ferdiad').sources.find_or_create_by(origin: 'Dungeon', name: 'Amdapor Keep (Hard)')
    Card.find_by(name: 'Demon Wall').sources.find_or_create_by(origin: 'Dungeon', name: 'Amdapor Keep')
    Card.find_by(name: 'Demon Wall').sources.find_or_create_by(origin: 'Dungeon', name: 'Amdapor Keep (Hard)')
    Card.find_by(name: 'Morbol').sources.find_or_create_by(origin: 'Dungeon', name: 'Aurum Vale')
    Card.find_by(name: 'The Griffin').sources.find_or_create_by(origin: 'Dungeon', name: "Baelsar's Wall")
    Card.find_by(name: 'Livia sas Junius').sources.find_or_create_by(origin: 'Dungeon', name: 'Castrum Meridiaum')
    Card.find_by(name: 'Chimera').sources.find_or_create_by(origin: 'Dungeon', name: "Cutter's Cry")
    Card.find_by(name: 'Ahriman').sources.find_or_create_by(origin: 'Dungeon', name: 'Dzemael Darkhold')
    Card.find_by(name: 'Succubus').sources.find_or_create_by(origin: 'Dungeon', name: 'Haukke Manor')
    Card.find_by(name: 'Succubus').sources.find_or_create_by(origin: 'Dungeon', name: 'Haukke Manor (Hard)')
    Card.find_by(name: 'Mistbeard').sources.find_or_create_by(origin: 'Dungeon', name: 'Hullbreaker Isle (Hard)')
    Card.find_by(name: 'Waukkeon').sources.find_or_create_by(origin: 'Dungeon', name: 'Neverreap')
    Card.find_by(name: 'Siren').sources.find_or_create_by(origin: 'Dungeon', name: 'Pharos Sirius')
    Card.find_by(name: 'Progenitrix').sources.find_or_create_by(origin: 'Dungeon', name: 'Pharos Sirius (Hard)')
    Card.find_by(name: 'Belladonna').sources.find_or_create_by(origin: 'Dungeon', name: "Saint Mocianne's Arboretum")
    Card.find_by(name: 'Tokkapchi').sources.find_or_create_by(origin: 'Dungeon', name: "Saint Mocianne's Arboretum (Hard)")
    Card.find_by(name: 'Sahagin').sources.find_or_create_by(origin: 'Dungeon', name: 'Sastasha')
    Card.find_by(name: 'Sahagin').sources.find_or_create_by(origin: 'Dungeon', name: 'Sastasha (Hard)')
    Card.find_by(name: 'Kraken').sources.find_or_create_by(origin: 'Dungeon', name: 'Sastasha (Hard)')
    Card.find_by(name: 'Lava Scorpion').sources.find_or_create_by(origin: 'Dungeon', name: 'Sohm Al (Hard)')
    Card.find_by(name: 'Hraesvelgr').sources.find_or_create_by(origin: 'Dungeon', name: 'Sohr Khai')
    Card.find_by(name: 'Calcabrina').sources.find_or_create_by(origin: 'Dungeon', name: 'The Antitower')
    Card.find_by(name: 'Mist Dragon').sources.find_or_create_by(origin: 'Dungeon', name: 'The Burn')
    Card.find_by(name: 'Tioman').sources.find_or_create_by(origin: 'Dungeon', name: 'Sohm Al')
    Card.find_by(name: 'Nidhogg').sources.find_or_create_by(origin: 'Dungeon', name: 'The Aery')
    Card.find_by(name: 'Griffin').sources.find_or_create_by(origin: 'Dungeon', name: 'Dusk Vigil')
    Card.find_by(name: 'Byblos').sources.find_or_create_by(origin: 'Dungeon', name: 'The Great Gubal Library')
    Card.find_by(name: 'Strix').sources.find_or_create_by(origin: 'Dungeon', name: 'The Great Gubal Library (Hard)')
    Card.find_by(name: 'Curator').sources.find_or_create_by(origin: 'Dungeon', name: 'The Fractal Continuum')
    Card.find_by(name: 'Kuribu').sources.find_or_create_by(origin: 'Dungeon', name: 'The Lost City of Amdapor (Hard)')
    Card.find_by(name: 'Blue Dragon').sources.find_or_create_by(origin: 'Dungeon', name: 'Stone Vigil')
    Card.find_by(name: 'Blue Dragon').sources.find_or_create_by(origin: 'Dungeon', name: 'Stone Vigil (Hard)')
    Card.find_by(name: 'Vicegerent to the Warden').sources
      .find_or_create_by(origin: 'Dungeon', name: 'The Sunken Temple of Qarn (Hard)')
    Card.find_by(name: 'Charibert').sources.find_or_create_by(origin: 'Dungeon', name: 'The Vault')
    Card.find_by(name: 'Manxome Molaa Ja Ja').sources.find_or_create_by(origin: 'Dungeon', name: "The Wanderer's Palace (Hard)")
    Card.find_by(name: 'Tonberry').sources.find_or_create_by(origin: 'Dungeon', name: "The Wanderer's Palace")
    Card.find_by(name: 'Tonberry').sources.find_or_create_by(origin: 'Dungeon', name: "The Wanderer's Palace (Hard)")
    Card.find_by(name: 'Tozol Huatotl').sources.find_or_create_by(origin: 'Dungeon', name: 'Xelphatol')
    Card.find_by(name: 'Genbu').sources.find_or_create_by(origin: 'Dungeon', name: "Hell's Lid")
    Card.find_by(name: 'Guidance Node').sources.find_or_create_by(origin: 'Dungeon', name: 'The Fractal Continuum (Hard)')
    Card.find_by(name: 'Qitian Dasheng').sources.find_or_create_by(origin: 'Dungeon', name: "The Swallow's Compass")
    Card.find_by(name: 'Fenrir').sources.find_or_create_by(origin: 'Dungeon', name: 'Snowcloak')
    Card.find_by(name: 'Hrodric Poisontongue').sources.find_or_create_by(origin: 'Dungeon', name: 'The Drowned City of Skalla')

    # Trials
    Card.find_by(name: 'Zurvan').sources.find_or_create_by(origin: 'Trial', name: 'Containment Bay Z1T9')
    Card.find_by(name: 'Zurvan').sources.find_or_create_by(origin: 'Trial', name: 'Containment Bay Z1T9 (Extreme)')
    Card.find_by(name: 'Shiva').sources.find_or_create_by(origin: 'Trial', name: 'Akh Afah Amphitheatre (Hard)')
    Card.find_by(name: 'Shiva').sources.find_or_create_by(origin: 'Trial', name: 'Akh Afah Amphitheatre (Extreme)')
    Card.find_by(name: 'Rhitahtyn sas Arvina').sources.find_or_create_by(origin: 'Trial', name: 'Cape Westwind')
    Card.find_by(name: 'Bartz Klauser').sources.find_or_create_by(origin: 'Trial', name: 'Battle in the Big Keep')
    Card.find_by(name: 'Gilgamesh & Enkidu').sources.find_or_create_by(origin: 'Trial', name: 'Battle on the Big Bridge')
    Card.find_by(name: 'Suzaku').sources.find_or_create_by(origin: 'Trial', name: "Hells' Kier")
    Card.find_by(name: 'Suzaku').sources.find_or_create_by(origin: 'Trial', name: "Hells' Kier (Extreme)")
    Card.find_by(name: 'Sophia').sources.find_or_create_by(origin: 'Trial', name: 'Containment Bay P1T6')
    Card.find_by(name: 'Sophia').sources.find_or_create_by(origin: 'Trial', name: 'Containment Bay P1T6 (Extreme)')
    Card.find_by(name: 'Ifrit').sources.find_or_create_by(origin: 'Trial', name: 'The Bowl of Embers (Hard)')
    Card.find_by(name: 'Ifrit').sources.find_or_create_by(origin: 'Trial', name: 'The Bowl of Embers (Extreme)')
    Card.find_by(name: 'Ultros & Typhon').sources.find_or_create_by(origin: 'Trial', name: "The Dragon's Neck")
    Card.find_by(name: 'Terra Branford').sources.find_or_create_by(origin: 'Trial', name: "The Dragon's Neck")
    Card.find_by(name: 'Garuda').sources.find_or_create_by(origin: 'Trial', name: 'The Howling Eye (Hard)')
    Card.find_by(name: 'Garuda').sources.find_or_create_by(origin: 'Trial', name: 'The Howling Eye (Extreme)')
    Card.find_by(name: 'Bismarck').sources.find_or_create_by(origin: 'Trial', name: 'The Limitless Blue (Hard)')
    Card.find_by(name: 'Bismarck').sources.find_or_create_by(origin: 'Trial', name: 'The Limitless Blue (Extreme)')
    Card.find_by(name: 'Archbishop Thordan VII').sources
      .find_or_create_by(origin: 'Trial', name: "The Minstrel's Ballad: Thordan's Reign")
    Card.find_by(name: 'Ultima Weapon').sources.find_or_create_by(origin: 'Trial', name: "The Minstrel's Ballad: Ultima's Bane")
    Card.find_by(name: 'Titan').sources.find_or_create_by(origin: 'Trial', name: 'The Navel (Hard)')
    Card.find_by(name: 'Titan').sources.find_or_create_by(origin: 'Trial', name: 'The Navel (Extreme)')
    Card.find_by(name: 'Ramuh').sources.find_or_create_by(origin: 'Trial', name: 'The Striking Tree (Hard)')
    Card.find_by(name: 'Ramuh').sources.find_or_create_by(origin: 'Trial', name: 'The Striking Tree (Extreme)')
    Card.find_by(name: 'Leviathan').sources.find_or_create_by(origin: 'Trial', name: 'The Whorleater (Hard)')
    Card.find_by(name: 'Leviathan').sources.find_or_create_by(origin: 'Trial', name: 'The Whorleater (Extreme)')
    Card.find_by(name: 'Ravana').sources.find_or_create_by(origin: 'Trial', name: 'Thok ast Thok (Hard)')
    Card.find_by(name: 'Ravana').sources.find_or_create_by(origin: 'Trial', name: 'Thok ast Thok (Extreme)')
    Card.find_by(name: 'Good King Moggle Mog XII').sources.find_or_create_by(origin: 'Trial', name: 'Thornmarch (Hard)')
    Card.find_by(name: 'Good King Moggle Mog XII').sources.find_or_create_by(origin: 'Trial', name: 'Thornmarch (Extreme)')
    Card.find_by(name: 'Odin').sources.find_or_create_by(origin: 'Trial', name: "Urth's Fount")
    Card.find_by(name: 'Tsukuyomi').sources.find_or_create_by(origin: 'Trial', name: "Castrum Fluminis")
    Card.find_by(name: 'Tsukuyomi').sources.find_or_create_by(origin: 'Trial', name: "The Minstrel's Ballad: Tsukuyomi's Pain")
    Card.find_by(name: 'Byakko').sources.find_or_create_by(origin: 'Trial', name: 'The Jade Stoa')
    Card.find_by(name: 'Byakko').sources.find_or_create_by(origin: 'Trial', name: 'The Jade Stoa (Extreme)')
    Card.find_by(name: 'Lakshmi').sources.find_or_create_by(origin: 'Trial', name: 'Emanation')
    Card.find_by(name: 'Lakshmi').sources.find_or_create_by(origin: 'Trial', name: 'Emanation (Extreme)')
    Card.find_by(name: 'Susano').sources.find_or_create_by(origin: 'Trial', name: 'The Pool of Tribute')
    Card.find_by(name: 'Susano').sources.find_or_create_by(origin: 'Trial', name: 'The Pool of Tribute (Extreme)')
    Card.find_by(name: 'Shinryu').sources.find_or_create_by(origin: 'Trial', name: "The Royal Menagerie")
    Card.find_by(name: 'Shinryu').sources.find_or_create_by(origin: 'Trial', name: "The Minstrel's Ballad: Shinryu's Domain")
    Card.find_by(name: 'Sephirot').sources.find_or_create_by(origin: 'Trial', name: 'Containment Bay S1T7')
    Card.find_by(name: 'Sephirot').sources.find_or_create_by(origin: 'Trial', name: 'Containment Bay S1T7 (Extreme)')

    # Raids
    Card.find_by(name: 'Phlegethon').sources.find_or_create_by(origin: 'Raid', name: 'Labyrinth of the Ancients')
    Card.find_by(name: 'Diabolos Hollow').sources.find_or_create_by(origin: 'Raid', name: 'Dun Scaith')
    Card.find_by(name: 'Brute Justice').sources.find_or_create_by(origin: 'Raid', name: 'Alexander - The Burden of the Son')
    Card.find_by(name: 'Alexander Prime').sources.find_or_create_by(origin: 'Raid', name: 'Alexander - The Soul of the Creator')
    Card.find_by(name: 'Omega').sources.find_or_create_by(origin: 'Raid', name: 'Alphascape V3.0')
    Card.find_by(name: 'Omega').sources.find_or_create_by(origin: 'Raid', name: 'Alphascape V4.0')
    Card.find_by(name: 'Xande').sources.find_or_create_by(origin: 'Raid', name: 'Syrcus Tower')
    Card.find_by(name: 'Echidna').sources.find_or_create_by(origin: 'Raid', name: 'The Void Ark')
    Card.find_by(name: 'Calofisteri').sources.find_or_create_by(origin: 'Raid', name: 'The Weeping City of Mhach')
    Card.find_by(name: 'Cloud of Darkness').sources.find_or_create_by(origin: 'Raid', name: 'World of Darkness')
    Card.find_by(name: 'Onion Knight').sources.find_or_create_by(origin: 'Raid', name: 'World of Darkness')
    Card.find_by(name: 'Yiazmat').sources.find_or_create_by(origin: 'Raid', name: 'The Ridorana Lighthouse')
    Card.find_by(name: 'Rofocale').sources.find_or_create_by(origin: 'Raid', name: 'The Royal City of Rabanastre')
    Card.find_by(name: 'Argath Thadalfus').sources.find_or_create_by(origin: 'Raid', name: 'The Royal City of Rabanastre')

    # FATEs
    Card.find_by(name: 'Darkscale').sources
      .find_or_create_by(origin: 'FATE', name: 'FATE: Mogicide / Rastaban Vibration (Churning Mists)')
    Card.find_by(name: 'Fat Chocobo').sources
      .find_or_create_by(origin: 'FATE', name: 'FATE: Special Tarasque Force (Dravanian Forelands)')
    Card.find_by(name: 'Phoebad').sources.find_or_create_by(origin: 'FATE', name: 'FATE: Tall Tale (The Lochs)')
    Card.find_by(name: 'Mammoth').sources.find_or_create_by(origin: 'FATE', name: 'FATE: Wham Bam Thank You Mammoth (Azim Steppe)')

    # Tournaments
    Card.find_by(name: 'Firion').sources.find_or_create_by(origin: 'Tournament', name: 'Triple Triad Tournament')
    Card.find_by(name: 'Cecil Harvey').sources.find_or_create_by(origin: 'Tournament', name: 'Triple Triad Tournament')
    Card.find_by(name: 'Tidus').sources.find_or_create_by(origin: 'Tournament', name: 'Triple Triad Tournament')
    Card.find_by(name: 'Lightning').sources.find_or_create_by(origin: 'Tournament', name: 'Triple Triad Tournament')

    # Achievements
    Card.find_by(name: 'Heavensward Thancred').sources.find_or_create_by(origin: 'Achievement', name: 'Achievement: Triple Team V')
    Card.find_by(name: 'Midgardsormr').sources.find_or_create_by(origin: 'Achievement', name: 'Achievement: Triple Decker IV')
    Card.find_by(name: 'Vidofnir').sources.find_or_create_by(origin: 'Achievement', name: 'Achievement: Triple Decker V')
    Card.find_by(name: "Heavensward Y'shtola").sources
      .find_or_create_by(origin: 'Achievement', name: 'Achievement: Triple-Decker VI')
    Card.find_by(name: 'Lyse').sources.find_or_create_by(origin: 'Achievement', name: 'Achievement: Triple-Decker VII')
    Card.find_by(name: 'Gosetsu').sources.find_or_create_by(origin: 'Achievement', name: 'Achievement: Triple Decker VIII')
    Card.find_by(name: 'Shantotto').sources.find_or_create_by(origin: 'Achievement', name: 'Achievement: Kumite Kumite Kumite')
    Card.find_by(name: 'Squall Leonhart').sources.find_or_create_by(origin: 'Achievement', name: 'Achievement: Triple Team II')
    Card.find_by(name: 'Haurchefant').sources.find_or_create_by(origin: 'Achievement', name: 'Achievement: Triple Team III')
    Card.find_by(name: 'Krile').sources.find_or_create_by(origin: 'Achievement', name: 'Achievement: Triple Team VII')
    Card.find_by(name: 'Vaan').sources.find_or_create_by(origin: 'Achievement', name: 'Achievement: Wheel of Fortune V')

    # Eureka
    Card.find_by(name: 'Happy Bunny').sources.find_or_create_by(origin: 'Eureka', name: 'Eureka Pagos: Silver Coffer')
    Card.find_by(name: 'Yukinko').sources.find_or_create_by(origin: 'Eureka', name: 'Eureka Pagos: Eternity FATE')
    Card.find_by(name: 'Pazuzu').sources.find_or_create_by(origin: 'Eureka', name: 'Eureka Anemos: Wail in the Willows FATE')
    Card.find_by(name: 'Louhi').sources.find_or_create_by(origin: 'Eureka', name: 'Eureka Pagos: Louhi on Ice FATE')
    Card.find_by(name: 'Penthesilea').sources.find_or_create_by(origin: 'Eureka', name: 'Eureka Pyros: Lost Epic FATE')

    # Heaven on High
    Card.find_by(name: 'Wanyudo & Katasharin').sources.find_or_create_by(origin: 'Other', name: 'Heaven on High: Silver/Gold Sack')
    Card.find_by(name: 'Hatamoto').sources.find_or_create_by(origin: 'Other', name: 'Heaven on High: Silver/Gold Sack')
    Card.find_by(name: 'Hiruko').sources.find_or_create_by(origin: 'Other', name: 'Heaven on High: Gold Sack')

    # Events
    Card.find_by(name: 'Gold Saucer Attendant').sources.find_or_create_by(origin: 'Other', name: 'Event: Make It Rain (500 MGP)')
    Card.find_by(name: 'Roland').sources.find_or_create_by(origin: 'Other', name: 'Event: Make It Rain (1,000 MGP)')
    Card.find_by(name: 'Gigi').sources.find_or_create_by(origin: 'Other', name: 'Event: Make It Rain (18,000 MGP)')

    # Shop prices
    Card.find_by(name: 'Chocobo').update(buy_price: 600)
    Card.find_by(name: 'Opo-opo').update(buy_price: 600)
    Card.find_by(name: 'Moogle').update(buy_price: 840)
    Card.find_by(name: 'Mossling').update(buy_price: 840)
    Card.find_by(name: 'Adamantoise').update(buy_price: 840)
    Card.find_by(name: 'Chapuli').update(buy_price: 1200)
    Card.find_by(name: 'Muud Suud').update(buy_price: 1500)
    Card.find_by(name: 'Raya-O-Senna & A-Ruhn-Senna').update(buy_price: 4800)
    Card.find_by(name: 'Godbert Manderville').update(buy_price: 9600)
    Card.find_by(name: 'Julyan Manderville').update(buy_price: 14_400)
    Card.find_by(name: "F'lhaminn").update(buy_price: 20_000)
    Card.find_by(name: 'Senor Sabotender').update(buy_price: 200_000)
    Card.find_by(name: 'Nanamo Ul Namo').update(buy_price: 400_000)
    Card.find_by(name: 'Raubahn & Pipin').update(buy_price: 400_000)
    Card.find_by(name: 'Cloud Strife').update(buy_price: 1_000_000)
  end
end
